[package]
name = "xbeam"
version = "0.1.0"
authors = ["Stephen Cirner <scirner@getcrossbeam.com>"]

[dependencies]
clap = "2.32"
futures = "0.1.21"
hyper = "0.12"
hyper-tls = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
